"""
Report Generation Module – creates a professional PDF certificate for a settlement result.
Uses fpdf2 for lightweight, serverless-friendly PDF generation.
"""
from fpdf import FPDF
from datetime import datetime
import io

class OmniReport(FPDF):
    def header(self):
        # Logo placeholder or brand name
        self.set_font('helvetica', 'B', 15)
        self.set_text_color(59, 130, 246) # Blue accent
        self.cell(0, 10, 'Omni-Settlement Index Suite', border=False, align='L')
        self.set_font('helvetica', 'I', 8)
        self.set_text_color(100, 100, 100)
        self.cell(0, 10, 'Standard Settlement Certificate', border=False, align='R')
        self.ln(15)
        
        # Divider line
        self.set_draw_color(59, 130, 246)
        self.line(10, 22, 200, 22)

    def footer(self):
        self.set_y(-15)
        self.set_font('helvetica', 'I', 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, f'Page {self.page_no()} | Generated by Omni-Settlement Index Suite v1.0 | {datetime.now().strftime("%Y-%m-%d %H:%M")}', align='C')

def generate_pdf_report(ssi_data: dict) -> bytes:
    """
    Generate a professional PDF report from the SSI result data.
    """
    pdf = OmniReport()
    pdf.add_page()
    
    # --- Title & Metadata ---
    pdf.set_font('helvetica', 'B', 20)
    pdf.set_text_color(20, 20, 20)
    pdf.cell(0, 20, 'Settlement Verification Report', ln=True)
    
    pdf.set_font('helvetica', '', 10)
    pdf.cell(0, 6, f"Transaction Ref: {datetime.now().strftime('%Y%m%d')}-SSI-{hash(str(ssi_data))%10000:04d}", ln=True)
    pdf.cell(0, 6, f"Settlement Model: Standard Settlement Rate (SSI) Formula v1.0", ln=True)
    pdf.ln(10)

    # --- Core Result Highlight Box ---
    pdf.set_fill_color(240, 245, 255) # Light blue bg
    pdf.rect(10, 65, 190, 40, 'F')
    
    pdf.set_xy(15, 70)
    pdf.set_font('helvetica', 'B', 12)
    pdf.cell(0, 10, f"Final Standard Settlement Rate (S_rate): {ssi_data['s_rate']:.8f}")
    
    pdf.set_xy(15, 80)
    pdf.set_font('helvetica', 'B', 16)
    pdf.set_text_color(16, 185, 129) # Green
    pdf.cell(0, 12, f"Total Received: {ssi_data['settlement_summary']['crypto_received']:,.6f} {ssi_data['meta']['target_crypto']}")
    
    pdf.set_xy(15, 92)
    pdf.set_font('helvetica', 'I', 10)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 8, f"Equivalent covering ~{ssi_data['settlement_summary']['care_coverage_months']} months of standard care in {ssi_data['meta']['dest_country']}")
    pdf.ln(20)

    # --- SSI Formula Components ---
    pdf.set_xy(10, 115)
    pdf.set_font('helvetica', 'B', 12)
    pdf.set_text_color(20, 20, 20)
    pdf.cell(0, 10, 'Formula Components Breakdown', ln=True)
    
    pdf.set_font('helvetica', '', 10)
    cols = [('V_base', ssi_data['components']['v_base'], 'Bridge Rate Index'),
            ('I_care', ssi_data['components']['i_care'], 'Care-Gap Index Weight'),
            ('T_global', ssi_data['components']['t_global'], 'Global Tax Index'),
            ('B_eff', ssi_data['components']['b_eff'], 'Bridge Efficiency Score')]
    
    pdf.set_fill_color(245, 245, 245)
    pdf.set_font('helvetica', 'B', 9)
    pdf.cell(30, 8, 'Var', 1, 0, 'C', True)
    pdf.cell(40, 8, 'Value', 1, 0, 'C', True)
    pdf.cell(120, 8, 'Description', 1, 1, 'C', True)
    
    pdf.set_font('helvetica', '', 9)
    for var, val, desc in cols:
        pdf.cell(30, 8, var, 1, 0, 'C')
        pdf.cell(40, 8, f"{val:.8f}", 1, 0, 'C')
        pdf.cell(120, 8, desc, 1, 1, 'L')
    pdf.ln(10)

    # --- Financial Efficiency & ESG ---
    pdf.set_font('helvetica', 'B', 12)
    pdf.cell(0, 10, 'Savings & ESG Performance', ln=True)
    
    pdf.set_font('helvetica', '', 10)
    pdf.cell(100, 7, f"SWIFT Baseline Fee (Estimated):", 0, 0)
    pdf.cell(0, 7, f"${ssi_data['cost_efficiency']['swift_fee_usd']:.2f}", 0, 1)
    
    pdf.cell(100, 7, f"Bridge Settlement Fee:", 0, 0)
    pdf.cell(0, 7, f"${ssi_data['cost_efficiency']['bridge_fee_usd']:.2f}", 0, 1)
    
    pdf.set_font('helvetica', 'B', 10)
    pdf.cell(100, 7, f"Total Efficiency Savings:", 0, 0)
    pdf.cell(0, 7, f"${ssi_data['cost_efficiency']['total_savings_usd']:.2f} ({ssi_data['cost_efficiency']['savings_pct']}%)", 0, 1)
    
    pdf.set_font('helvetica', '', 10)
    pdf.cell(100, 7, f"Carbon Reduction vs SWIFT:", 0, 0)
    pdf.set_text_color(16, 185, 129)
    pdf.cell(0, 7, f"{ssi_data['esg']['carbon_reduction_pct']}% ({ssi_data['esg']['carbon_saved_g']}g CO2 saved)", 0, 1)
    pdf.set_text_color(20, 20, 20)
    pdf.ln(10)

    # --- Legal & Compliance ---
    pdf.set_font('helvetica', 'B', 12)
    pdf.cell(0, 10, 'Compliance & Regulatory Status', ln=True)
    pdf.set_font('helvetica', '', 9)
    pdf.multi_cell(0, 5, ssi_data['compliance']['compliance_note'])
    pdf.ln(5)
    pdf.cell(0, 5, f"Crypto Asset Status: {ssi_data['compliance']['regulatory_status']}", ln=True)
    
    # Seal / Disclamer
    pdf.ln(15)
    pdf.set_font('helvetica', 'I', 8)
    pdf.set_text_color(150, 150, 150)
    pdf.multi_cell(0, 4, "Disclaimer: This report is generated based on simulated and standard indexed data. It is intended for estimation and B2B feasibility studies. Real-time market volatility may cause slight variances in final execution.")

    # Return as bytes
    return pdf.output()
